site_name: "ZIRCON — Dark Liquidity Intent Layer"
site_url: https://ekkalamrani328.github.io/zircon-fhevm/
repo_url: https://github.com/Ekkalamrani328/zircon-fhevm

docs_dir: zircon-fhe-intents/docs

theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - Architecture: architecture.md
  - FHE Intro: FHE-intro.md
  - Integration (fhEVM): Zircon-fhe-integration.md
  - Tutorial (Demo): tutorial.md
  - Case Study: Case-Study.md
  - Vision: Zircon-vision.md
  - FAQ: FAQ.md
