site_name: ZIRCON — Dark Liquidity Intent Layer

docs_dir: zircon-fhe-intents/docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - content.code.copy

nav:
  - Overview: index.md
  - Summary: index.md        # hapus baris ini kalau sudah digabung ke index
  - FHE Intro: FHE-intro.md
  - Architecture: architecture.md
  - Integration (fhEVM): Zircon-fhe-integration.md
  - Tutorial (Demo): tutorial.md
  - Case Study: Case-Study.md
  - Vision: Zircon-vision.md
  - FAQ: FAQ.md
